# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build and Deploy to OSSRH

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        check-latest: true

    - name: Build with Maven
      run: mvn clean install

  deploy:
    name: Maven Deploy to OSSRH
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Set up JDK 8 and Maven for Deployment to OSSRH
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        check-latest: true
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: OSSRH_USERNAME # env variable for username in deploy
        server-password: OSSRH_PASSWORD # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Deploy to the Maven Central Repository (OSSRH)
      run: mvn --batch-mode deploy -Possrh-deploy
      env:
        OSSRH_USERNAME: cernier
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}